import os
import sys
from sqlalchemy import create_engine, text
from dotenv import load_dotenv

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))
load_dotenv()

DB_URI = os.getenv("SUPABASE_DB_URI")


def init_database():
    print(f"🚀 새 Supabase DB 초기화 중... ({DB_URI.split('@')[-1]})")

    engine = create_engine(DB_URI)

    # 주식 데이터 전용 테이블 생성 SQL
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS market_price_daily (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trade_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        symbol VARCHAR(10) NOT NULL,
        open_price NUMERIC,
        high_price NUMERIC,
        low_price NUMERIC,
        close_price NUMERIC,
        volume BIGINT,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
    );

    -- 중복 방지용 인덱스 (같은 날짜, 같은 종목은 1개만)
    CREATE UNIQUE INDEX IF NOT EXISTS idx_symbol_date 
    ON market_price_daily (symbol, trade_date);

    -- 유니크 제약조건 추가 (Upsert용)
    ALTER TABLE market_price_daily 
    DROP CONSTRAINT IF EXISTS unique_symbol_date;

    ALTER TABLE market_price_daily 
    ADD CONSTRAINT unique_symbol_date UNIQUE (symbol, trade_date);
    """

    try:
        with engine.begin() as conn:
            conn.execute(text(create_table_sql))
        print("✅ 테이블 생성 완료! (market_price_daily)")
        print("🎉 이제 주식 데이터를 받을 준비가 끝났습니다.")

    except Exception as e:
        print(f"❌ 오류 발생: {e}")


if __name__ == "__main__":
    init_database()